### ISSUE TITLE
Make image library configurable

### ISSUE THREAD

**Issue by HypeMC** [ihabunek/pdf417-php#12]
The library uses Intervention image which can be configured to use either GD or Imagick, but currently there's no way to configure it use Imagick. It'd be great if there was a way to pass an option to Intervention to use a different driver, as per the documentation http://image.intervention.io/getting_started/configuration .

Also the Composer requirements currently have `ext-gd` listed as a required dependency. It wouldn't make much sense any more to keep this if a different driver could be used, so maybe moving it to the `suggest` section of the composer.json file would be a better approach. This would especially make sense when considering that the svg renderer doesn't use Intervention or GD at all.

**Comment by ihabunek** [comment]
Any chance of a pull request? I'm not very active in PHP these days and it would take me a while to set things up.

**Comment by ihabunek** [comment]
[This project is no longer maintained](https://github.com/ihabunek/pdf417-php/blob/master/README.md#this-project-is-no-longer-maintained). Sorry.
