### ISSUE TITLE
Encode > 928 chars?

### ISSUE THREAD

**Issue by medmen** [ihabunek/pdf417-php#15]
Sorry if this is a stupid question. 
Whenever i try to encode a string containing more than 928 characters, i get an error message.
So is this the maximum content pdf417 can encode?

**Comment by jesustejerina** [comment]
by default columns number is 6 (573 characters OK). I changed to 10 and that is OK (800 characters).
$pdf=new PDF417();
$pdf->setColumns(10);
... encode(your_text);

**Comment by ihabunek** [comment]
[This project is no longer maintained](https://github.com/ihabunek/pdf417-php/blob/master/README.md#this-project-is-no-longer-maintained). Sorry.
