### ISSUE TITLE
Loose Intervention (mbstring & fileinfo)

### ISSUE THREAD

**Issue by bozhinov** [ihabunek/pdf417-php#16]
Hello,

Attaching pure GD code with no additional libs or extensions
also the output PNG image is 6 times smaller in my tests

I realize this is not a drop in replacement but it should be fairly easy to get it there

Thanks for the code
Momchil
[ImageRenderer.txt](https://github.com/ihabunek/pdf417-php/files/3800581/ImageRenderer.txt)

**Comment by bozhinov** [comment]
[ImageRenderer.txt](https://github.com/ihabunek/pdf417-php/files/3800595/ImageRenderer.txt)
Even cleaner version

**Comment by ihabunek** [comment]
[This project is no longer maintained](https://github.com/ihabunek/pdf417-php/blob/master/README.md#this-project-is-no-longer-maintained). Sorry.
