### ISSUE TITLE
PDF417 Barcode reading, through an image

### ISSUE THREAD

**Issue by johannoscar** [ihabunek/pdf417-php#17]
When will you implement PDF417 barcode reading through an image? Thanks!

**Comment by Cyphryx** [comment]
I would pay someone to implement a decoder algorithm that is half decent. The other open-source decoders for PDF417 are very low quality.

**Comment by ihabunek** [comment]
[This project is no longer maintained](https://github.com/ihabunek/pdf417-php/blob/master/README.md#this-project-is-no-longer-maintained). Sorry.
