### ISSUE TITLE
UTF-8 Encode Issue

### ISSUE THREAD

**Issue by a7med-hussien** [ihabunek/pdf417-php#18]
Issue While trying to generate with Arabic text it appears like in image !!

![WhatsApp Image 2020-02-10 at 12 07 20 AM](https://user-images.githubusercontent.com/11396252/74111047-2241b600-4b9a-11ea-904b-bf34eb635660.jpeg)

**Comment by ihabunek** [comment]
[This project is no longer maintained](https://github.com/ihabunek/pdf417-php/blob/master/README.md#this-project-is-no-longer-maintained). Sorry.
