### ISSUE TITLE
Encoding and decoding gives wrong result

### ISSUE THREAD

**Issue by ruudk** [ihabunek/pdf417-php#2]
Hi,

I'm encoding `061027XX5237011F1E` to PDF417 using:

``` php
<?php

require 'vendor/autoload.php';

use BigFish\PDF417\PDF417;
use BigFish\PDF417\Renderers\ImageRenderer;

// Encode the data, returns a BarcodeData object
$pdf417 = new PDF417();
$data = $pdf417->encode('061027XX5237011F1E');

$renderer = new ImageRenderer([
    'format' => 'png'
]);

$image = $renderer->render($data);
$image->save('test.png');
```

It gives the following image:
![test](https://cloud.githubusercontent.com/assets/104180/14928085/0fa6cca4-0e56-11e6-879b-8ddc4539b047.png)

Decoding it at https://online-barcode-reader.inliteresearch.com/default.aspx gives 
<img width="672" alt="screen shot 2016-04-29 at 22 02 59" src="https://cloud.githubusercontent.com/assets/104180/14928107/366de098-0e56-11e6-9185-94a27b96f0cb.png">

**Comment by ruudk** [comment]
So I found out that it has something to do with numbers. Whenever I encode `RUUD` it perfectly creates a barcode that can be decoded to `RUUD`.
But as soon as I change it to `1RUUD` it will decode to `ALRUUD`

**Comment by ruudk** [comment]
Disabling the NumberEncoder solves the problem for me. Any idea @ihabunek ?

**Comment by ihabunek** [comment]
Hey! Thanks for reporting. Sorry for the late reply, I'll have a look at this tomorrow.

**Comment by ihabunek** [comment]
@ruudk This should now be solved. The encoder did not switch to the correct mode when the data to encode did not start with text (but with numbers in your case). Please test and let me know if it works for you now.

**Comment by ruudk** [comment]
It works :) Thanks for fixing it.

I'm going to try if I can port this thing to Golang 😅

**Comment by ihabunek** [comment]
Haha, feel free to do so. Just please, if you find any more bugs in the process, report them here. And i suspect there are some in there. :)
