### ISSUE TITLE
Error codeword [0][941]

### ISSUE THREAD

**Issue by jesustejerina** [ihabunek/pdf417-php#20]
Es un aporte ya que no hay documentación.
Tenía que codificar un texto con 800 caracteres y me salía el error codeword [0][941] asi que probaaando probando encontré que se debía ampliar el número de columnas de la clase PDF417 ya que por defecto es 6. En mi caso la amplié a 10 y se solucionó el problema. Ejm:
$timbre_texto=$DTE->getTED(); //aquí obtenía los 800 caracteres.
$pdf417=new PDF417();
$pdf417->setColumns(10); //aquí donde amplío el número de columnas.
$datos=$pdf417->encode($timbre_texto); //aquí era donde salía el error.
...
Espero les sirva.

**Comment by cquinoneso** [comment]
Muchas Gracias, me sirvió, ya estaba loco, con una cadena grande me aparecía ese error y con un "Hola" todo bien

**Comment by ihabunek** [comment]
[This project is no longer maintained](https://github.com/ihabunek/pdf417-php/blob/master/README.md#this-project-is-no-longer-maintained). Sorry.
