### ISSUE TITLE
i have a problem

### ISSUE THREAD

**Issue by eddgeo** [ihabunek/pdf417-php#21]
Fatal error: Uncaught Error: Class "PHPUnit\Framework\TestCase" not found in C:\xampp\htdocs\pdf417-php-master\tests\CodesTest.php:8 Stack trace: #0 {main} thrown in C:\xampp\htdocs\pdf417-php-master\tests\CodesTest.php on line 8

solutions?

**Comment by ihabunek** [comment]
[This project is no longer maintained](https://github.com/ihabunek/pdf417-php/blob/master/README.md#this-project-is-no-longer-maintained). Sorry.
