### ISSUE TITLE
Invalid code word [0][934]

### ISSUE THREAD

**Issue by Swader** [ihabunek/pdf417-php#7]
When trying to convert an HUB3A dataset into a barcode, I get the following error: `Invalid code word [0][934]`.

For some reason, the code word tables go out of bounds.
The Python version of this lib works fine, as does [this site](https://www.free-barcode-generator.net/pdf417/).

Example data: https://gist.github.com/Swader/03882246625c7b2a0cade1c5ac526a94

I'm open to suggestions.

**Comment by Swader** [comment]
I'm an idiot, sorry.

**Comment by angeldev20** [comment]
Hi Swader,
I'm still an idiot.
How did you fix Invalid code word [0][934]?
Thanks.

**Comment by Swader** [comment]
I don't remember what cured my idiocy, sorry :(
