### ISSUE TITLE
Wrong character in SUBMODE_PUNCT

### ISSUE THREAD

**Issue by wotan192** [ihabunek/pdf417-php#8]
Hello,

According to https://notendur.hi.is/hh/kennsla/grr/v08/pdf417.html the punctuation array has a wrong character. It should be "\\"" instead of "g". The page you referred at (http://grandzebu.net/informatique/codbar-en/pdf417.htm) has this error, and with this error '@gmail' decodes to '@"mail'.

I changed the character and tested enconding, it's ok. Unfortunately I can't send the pull request to here, so please fix it in src/Encoders/TextEncoder.php :

```
diff --git a/src/Encoders/TextEncoder.php b/src/Encoders/TextEncoder.php
index f07f141..8f08495 100644
--- a/src/Encoders/TextEncoder.php
+++ b/src/Encoders/TextEncoder.php
@@ -97,7 +97,7 @@ class TextEncoder implements EncoderInterface
         self::SUBMODE_PUNCT => [
             ";", "<", ">", "@", "[", "\\", "]", "_", "`",
             "~", "!", "\r", "\t", ",", ":", "\n", "-", ".",
-            "$", "/", "g", "|", "*", "(", ")", "?", "{", "}", "'",
+            "$", "/", "\"", "|", "*", "(", ")", "?", "{", "}", "'",
             self::SWITCH_UPPER,
         ],
     ];
```

**Comment by ihabunek** [comment]
Sigh, I actually corrected this recently in the python port, and totally forgot to apply it here as well. Thanks for the report.

I have merged your commit and it's now released as `0.3.0`.
https://github.com/ihabunek/pdf417-php/releases/tag/0.3.0
